# Generated by Django 5.1.3 on 2024-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDF',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs'),
        ),
    ]
