# Generated by Django 5.1.3 on 2024-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_profile_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
