# Generated by Django 5.1.3 on 2025-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_profile_is_subscriber_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='burmese_version',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
