# Generated by Django 5.1.3 on 2025-01-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_burmese_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='burmese_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
