# Generated by Django 5.1.3 on 2025-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_image_one_alter_product_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_one',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_two',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
