# Generated by Django 5.1.3 on 2025-01-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
