# Generated by Django 5.1.3 on 2025-01-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
