# Generated by Django 5.1.3 on 2025-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_description',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
