# Generated by Django 5.1.3 on 2025-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_file',
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
